config/routes.rb
Rails.application.routes.draw do

  # # Serve websocket cable requests in-process
  #mount ActionCable.server => '/cable'


  namespace :api do 

   get '/cards' => 'cards#index'
   get '/users' => 'users#index'
   get '/mycards' => 'my_cards#index'
   
  end

  get '/' => 'games#index'
  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  get '/users/:id' => 'users#show'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/mycards' => 'my_cards#index'

  get '/games/new' => 'games#new'
  post '/games/' => 'games#create'

  get '/games/:id/attack/' => 'games#attack'
  post '/games/:id/dealdamage' => 'games#deal_damage'
  post '/games/:id/endturn' => 'games#end_turn'
  get '/games/:id/victory' => 'games#victory'
  get '/game' => 'games#game'

  resources :cards

end

app/models/card.rb
class Card < ApplicationRecord
  has_many :my_cards
  has_many :users, through: :my_cards
  # has_many :images, as: :imageable_type

  has_attached_file :image, 
  styles: {large: "357x500>", medium: "214x300>", small: "143x200"}
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  def medium_image_url
        image.url(:medium)
  end

  def large_image_url
        image.url(:large)
   end



end

app/controllers/api/cards_controller.rb
class Api::CardsController < ApplicationController

  def index
    @cards = Card.all
  end

end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def index
    @opponent = User.find_by(name: "default")
    @cardback = Card.find_by(name: "back")
    @cards = Card.all
  end

  def attack
    @cards = Card.all
    @cardback = Card.find_by(name: "back")
    @opponent = User.find_by(name: "default")
  end
  
  def new

    @card = Card.new
  end

  def create
  @card = Card.create( card_params )
  redirect_to "/cards/#{@card.id}"
  end

  def edit
    @card = Card.find(params[:id])
  end

  def update
    @card = Card.find(params[:id])
    @card.update( card_params )
    redirect_to "/cards/#{@card.id}"
  end

  def show
    @card = Card.find(params[:id])
  end

  private

  # Use strong_parameters for attribute whitelisting
  # Be sure to update your create() and update() controller methods.

  def card_params
    params.require(:card).permit(:image, :name, :cost, :description, :action_text, :attack)
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/edit.html.erb
<%= form_for @card, html: { multipart: true } do |form| %>
  <div>
    <h3>image</h3> <%= form.file_field :image %>
  </div>
  <div>
    <h3>name</h3> <%= form.text_field :name %>
  </div>
  <div>
    <h3>cost</h3> <%= form.text_field :cost %>
  </div>
  <div>
    <h3>attack</h3> <%= form.text_field :attack %>
  </div>
  <div>
    <h3>description</h3><%= form.text_field :description %>
  </div>
  <div>
    <h3>action text</h3><%= form.text_field :action_text %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cards/new.html.erb
<%= form_for @card, url: cards_path, html: { multipart: true } do |form| %>
  <div>
    <h3>image</h3> <%= form.file_field :image %>
  </div>
  <div>
    <h3>name</h3> <%= form.text_field :name %>
  </div>
  <div>
    <h3>cost</h3> <%= form.text_field :cost %>
  </div>
  <div>
    <h3>attack</h3> <%= form.text_field :attack %>
  </div>
  <div>
    <h3>description</h3><%= form.text_field :description %>
  </div>
  <div>
    <h3>action text</h3><%= form.text_field :action_text %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cards/show.html.erb
<%= image_tag @card.image.url(:small) %>
<%= image_tag @card.image.url(:medium) %>
<%= image_tag @card.image.url(:large) %>

<h1><%= @card.name  %></h1>
<h2><%= @card.attack %></h2>
<h4><%= @card.description %></h4>
<h4><%= @card.action_text %></h4>